version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db

  backend:
    build: .
    container_name: node-app
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017/vlog_db
    depends_on:
      - mongo